-- ── dietary_requirements + order_dietary_requirements ─────────────────────────
-- Run once in the Supabase SQL editor. Safe to re-run (idempotent).
--
-- WHAT: structured capture of "make it eggless" / "nut-free" on an order. Today this
-- information reaches the baker ONLY as prose in orders' free-text "Special
-- instructions" box, so it cannot be queried, cannot drive a label on the print
-- sheet, cannot raise an alert, and cannot be reported on. The customer almost always
-- states it clearly at order time — it gets lost AFTERWARDS, between the notes field
-- and the person mixing batter at 6am. This table is the fix for that transmission
-- loss. See spattoo-docs/plans/new-feature-ideas.md §8.
--
-- TWO KINDS, deliberately one table with a `kind` discriminator, because they are the
-- same shape to store but drive different downstream behaviour:
--   • 'diet'     — eggless / vegan / Jain. In this market these are overwhelmingly
--                  RELIGIOUS AND DIETARY, not medical, and they are a large share of
--                  volume. This is a normal product attribute, like weight or flavour:
--                  it constrains which flavours are orderable and may change price and
--                  lead time. Getting it wrong is a refused cake and, in some
--                  communities, a permanent loss of the customer.
--   • 'allergen' — nut / gluten / dairy. Low volume, high severity. This is the kind
--                  that later wants batch segregation and an attestation trail.
-- Do not collapse the distinction: a UI that treats eggless as a safety warning gets
-- the common case wrong, and one that treats a nut allergy as a preference is worse.
--
-- DESIGN (hot vs bounded — see CLAUDE.md "persisted schema is forever"):
--   dietary_requirements is BOUNDED (an enum with metadata, ~10 rows forever). It
--   carries a surrogate `id smallint` PK AND a readable `key` UNIQUE. The join to the
--   HIGH-VOLUME side stores the compact `id`, never the text key — text bloats every
--   row and every index on a table that grows with orders. The API joins to expose
--   the key, so callers still speak 'eggless', never magic numbers. Requirements are
--   DATA: add/retire one, or re-label/re-order, by editing rows here.
--   (order_statuses had to be migrated from a text PK to this shape after the fact —
--   see order_status_surrogate.sql. This table is born correct.)
--
-- ORDER-LEVEL, NOT PER-TIER. Flavour is already per tier (OrderModal.jsx), and it is
-- tempting to mirror that. It would be wrong: a religious eggless requirement is not
-- satisfied by an eggless top tier sitting on an egg-based base. The requirement
-- belongs to the ORDER and constrains every tier's flavour options.
--
-- WHAT THIS DOES NOT DO: it records an assertion, it does not verify one. Our Terms of
-- Service §3.4 states Spattoo does not collect, verify or represent ingredients or
-- allergens. The role split that keeps that honest is customer ASSERTS → baker
-- CONFIRMS → Spattoo RECORDS AND VERIFIES NEITHER, which is why `source` exists below.
-- Nothing here should be rendered as "EGGLESS ✓" as though the platform checked
-- something; that turns a disclaimer into a representation. Rewording §3.4 is in scope
-- for the customer-facing path (legal copy is versioned via publish-legal-version.mjs).

-- ── the lookup ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS dietary_requirements (
  id         smallint    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key        text        NOT NULL UNIQUE,                 -- machine slug the API speaks
  label      text        NOT NULL,                        -- display label
  kind       text        NOT NULL CHECK (kind IN ('diet','allergen')),
  sort_order int         NOT NULL,                        -- display order in the picker
  is_active  boolean     NOT NULL DEFAULT true,           -- retire without deleting history
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Seed. ON CONFLICT keeps labels/ordering editable by re-running this file; ids, once
-- assigned by the identity sequence, are stable because `key` is the conflict target.
-- ⚠️ `egg` is the one row here that RESTRICTS NOTHING — it is the customer choosing the
-- ordinary cake. It lives here so `baker_dietary_exclusions` can express "we are a
-- pure-veg bakery" (a row against `egg`), which was previously unsayable, and so that
-- "with egg" is distinguishable from "nobody asked". Every surface that flags a
-- DEVIATION must filter it out or it fires on nearly every order and stops being read.
-- See migrations/078_egg_choice.sql and `restrictions()` in spattoo-core.
INSERT INTO dietary_requirements (key, label, kind, sort_order) VALUES
  ('egg',         'With egg',     'diet',      5),
  ('eggless',     'Eggless',      'diet',     10),
  ('vegan',       'Vegan',        'diet',     20),
  ('jain',        'Jain',         'diet',     30),
  ('nut_free',    'Nut-free',     'allergen', 40),
  ('gluten_free', 'Gluten-free',  'allergen', 50),
  ('dairy_free',  'Dairy-free',   'allergen', 60)
ON CONFLICT (key) DO UPDATE SET
  label      = EXCLUDED.label,
  kind       = EXCLUDED.kind,
  sort_order = EXCLUDED.sort_order;

COMMENT ON TABLE dietary_requirements IS
  'Bounded lookup of dietary/allergen requirements an order can carry. kind=diet is a product attribute (eggless/vegan/Jain — religious+dietary, high volume); kind=allergen is the safety tail (nut/gluten/dairy). Referenced by order_dietary_requirements via the compact smallint id.';

-- ── the join, on the high-volume side ─────────────────────────────────────────
-- SCALE: bounded per order (a handful of rows), unbounded in total — it grows with
-- orders, which is exactly why requirement_id is a smallint and not the text key.
-- ON DELETE CASCADE: requirements die with the order.
CREATE TABLE IF NOT EXISTS order_dietary_requirements (
  order_id       uuid        NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  requirement_id smallint    NOT NULL REFERENCES dietary_requirements(id),
  -- WHO put this on the order. The whole liability posture rests on this distinction:
  -- 'customer' is the customer asserting their own requirement; 'baker' is the baker
  -- recording what a customer told them over WhatsApp or the phone (which is what the
  -- notes field is used for today). Spattoo asserts nothing either way.
  source         text        NOT NULL CHECK (source IN ('customer','baker')),
  created_at     timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (order_id, requirement_id)
);

-- The PK already serves "what does THIS order require". This index serves the reverse,
-- which is the query the kitchen actually runs: "every eggless order for Saturday".
CREATE INDEX IF NOT EXISTS order_dietary_requirements_req_idx
  ON order_dietary_requirements (requirement_id, order_id);

COMMENT ON TABLE order_dietary_requirements IS
  'Dietary/allergen requirements asserted on an order. A row is an ASSERTION recorded by Spattoo, not a verification by it — `source` says who made it (customer vs baker recording what the customer said). Order-level on purpose: an eggless requirement is not satisfied by one eggless tier.';

-- ── NOT in this migration (additive later, no rework) ──────────────────────────
-- 1. Flavour compatibility — which flavours can satisfy which requirement, so a
--    customer requiring eggless who picks an incompatible flavour is caught AT ORDER
--    TIME rather than on the bench. Flavours are global with per-baker exclusions
--    (baker_flavour_exclusions), and whether a flavour can be made eggless is
--    genuinely baker-specific, so this wants its own table mirroring that pattern.
--    Deferred because it needs authored data we do not have yet, and adding it later
--    is a new table, not a migration of this one.
-- 2. Baker fulfilment confirmation (the "baker CONFIRMS" half of the role split).
--    That is an attestation — who confirmed, when, against exactly which wording —
--    and belongs in the content_attestations pattern, not as a column here.
-- 3. Customer-profile defaults (a vegetarian customer is vegetarian every time).
--    Must still be confirmed per order and never silently assumed — assuming is the
--    exact failure this feature exists to prevent.
