-- ── 022: AI credits ledger + xray_spec ────────────────────────────────────────
-- The metering layer behind the "smart tools" allowance (#13) and, new here, X-Ray for
-- orders that have no design. Rationale + pricing model: docs (spattoo-core)
-- AI_CREDITS_PLAN.md; tier values: SUBSCRIPTION_TIERS.md.
--
-- Apply manually to dev/prod Supabase (no migration runner). Safe to re-run.
--
-- ── THE TWO POOLS, AND WHY ONE OF THEM IS NOT A TABLE ───────────────────────────────
-- A baker spends from two different things, and they have different lifetimes:
--
--   1. The MONTHLY ALLOWANCE (subscription_plans.features.ai_credits_per_month). Resets
--      every calendar month. It is a COST CEILING, not a balance the baker owns.
--   2. The PURCHASED WALLET (top-up packs). Real money, does not reset.
--
-- The allowance is NOT stored as monthly "grant" rows. It is DERIVED: allowance_used =
-- the sum of this calendar month's debits, and remaining = plan value − that. Which means:
--   * no monthly grant job to run, fail, or run twice;
--   * no expiry sweep for the unused part;
--   * a plan change takes effect immediately and correctly, with no back-fill;
--   * the number is recomputable from the ledger alone, so it cannot drift out of sync.
-- This is deliberately the same shape as the X-Ray meter ("the first 5 orders confirmed in
-- the calendar month, recomputable from the order rows alone"). A mutable
-- `credits_remaining` integer would have neither property and would race under concurrency.
--
-- CALENDAR month, not billing period: an annual subscriber's period is 12 months long, so
-- metering per period would hand them 12x the allowance. Month boundaries are IST — the
-- bakers are in India and "this month" must mean what it means to them.
--
-- ── WHY THE ALLOWANCE IS PASSED IN, NOT LOOKED UP HERE ──────────────────────────────
-- reserve_ai_credits() takes p_allowance as an argument. It does NOT read
-- subscription_plans.features itself, because resolving a baker's entitlements involves the
-- subscription status gate (BLOCKED_STATUSES collapses everything to its fallback) and that
-- logic lives in ONE place: src/services/entitlements.js. Re-implementing it in SQL would
-- create a second source of truth that silently disagrees with the middleware and the client
-- the first time either changes. The caller resolves, the function enforces.

-- ── 1. credit_costs — what each action costs, as DATA ────────────────────────────────
-- Admin-authored master data, never a code constant. Model prices change, our retail price
-- should not have to ship a deploy to follow them (and mostly should NOT follow them — a
-- provider price drop is margin, not a price cut). One row per metered action.
--
-- COMPACT SURROGATE `id`, readable `action_key` UNIQUE beside it — the same shape as
-- order_statuses (supabase/order_status_surrogate.sql), and for the same reason. This is a
-- bounded lookup; credit_transactions is not, and it references this table on every row it
-- will ever have. Storing 'photo_to_xray_estimate' (22 bytes) there instead of a smallint
-- (2 bytes) would carry that on every row AND every index entry, forever. Do NOT reason from
-- today's row count — see CLAUDE.md "PERSISTED SCHEMA IS FOREVER". The surrogate never leaves
-- the server: services/aiCredits.js takes and returns action_key strings.
create table if not exists credit_costs (
  id         smallint    generated by default as identity primary key,
  action_key text        not null unique,                   -- 'photo_to_xray_estimate'
  credits    integer     not null check (credits > 0),      -- always whole credits, rounded UP
  label      text        not null,                          -- shown in the admin editor
  is_active  boolean     not null default true,             -- retire an action without deleting its history
  updated_at timestamptz not null default now()
);

-- Seed values are ILLUSTRATIVE and priced off landed cost at ~80% target gross margin
-- (AI_CREDITS_PLAN.md §2.3). 1 credit ~= Rs.1 of RETAIL value. Replace with figures from a
-- real provider invoice before charging anyone. Idempotent: re-running updates in place.
--
-- `label` is a SHORT JOB NOUN, and that is a UI contract, not a description. It must also be
-- UNIQUE among ACTIVE rows: the billing card lists them as "{label} — {credits} credits", so two
-- actions sharing a label render as the same job at two different prices and read as a bug. That
-- happened: photo_to_xray_estimate and element_build_guide were both "Build guide". Migration 026
-- now ENFORCES uniqueness with a partial unique index, so the rule no longer depends on anyone
-- reading this paragraph.
--
-- SUPERSEDED BY 030: labels are no longer required to be single countable nouns. That rule existed
-- because the card rendered "14 build guides left this month" by appending an "s"; that per-tool
-- countdown was removed (it implied separate budgets when every action draws on one pool) and the
-- label now renders verbatim. Both actions are X-Ray and now say so.
--
-- ONLY the built action is active. is_active means "currently offered", and an inactive row both
-- keeps the billing card honest (it would otherwise advertise three features that do not exist)
-- and makes reserve_ai_credits fail closed with UNKNOWN_ACTION if anything calls one early. Flip
-- each to true in the change that ships it.
insert into credit_costs (action_key, credits, label, is_active) values
  ('photo_to_xray_estimate', 15, 'X-Ray — read a cake photo',  true),
  ('photo_to_cake_design',   20, 'Cake design',  false),   -- not built
  ('enquiry_to_draft_order',  2, 'Draft order',  false),   -- not built; plans/enquiry-parser.md
  ('sticker_generate',       60, 'Decoration',   false),   -- not built; Fondant Studio v1
  ('element_build_guide',    20, 'X-Ray — how to make a decoration', true)  -- one per decoration, then free forever
on conflict (action_key) do update
  set credits = excluded.credits, label = excluded.label,
      is_active = excluded.is_active, updated_at = now();

-- ── 2. credit_transactions — the append-only ledger ─────────────────────────────────
-- Every movement, forever. Balance is an aggregate over this table, never a stored integer.
-- Hot, write-heavy, per-baker, grows without bound → bigserial PK (no uuid index bloat on the
-- write path) and every read is indexed by baker_id.
--
-- SIGNS: credits is signed and always equals allowance_credits + wallet_credits.
--   grant/purchase/refund/adjustment  → positive
--   debit                             → negative
-- A debit splits across the two pools: allowance first, wallet only for the overflow. Storing
-- the split (rather than deriving it later) is what makes "how much of the allowance is gone"
-- a single sum instead of a replay of the whole history.
--
-- STATE is how "don't charge failed generations" becomes true rather than aspirational:
--   reserved  → credits are held; the model call has not returned yet
--   committed → the baker kept the result; this is a real charge
--   released  → the call failed or the baker discarded it; excluded from every balance
-- Reserved rows COUNT against the balance, so two concurrent jobs cannot both spend the last
-- credit. Released rows are kept, not deleted — a released reservation is evidence of a
-- failure we absorbed, and the retry rate it measures is a direct input to landed cost.
create table if not exists credit_transactions (
  id                bigserial   primary key,
  baker_id          uuid        not null references bakers (id) on delete cascade,
  kind              text        not null check (kind in ('grant','purchase','debit','refund','adjustment')),
  state             text        not null default 'committed' check (state in ('reserved','committed','released')),
  action_id         smallint    references credit_costs (id),   -- debits/refunds only; null for grants and purchases
  credits           integer     not null,
  allowance_credits integer     not null default 0,          -- the part that came from / returns to the monthly allowance
  wallet_credits    integer     not null default 0,          -- the part that came from / returns to purchased credits
  order_id          uuid        references orders (id) on delete set null,
  -- Margin guardrail (AI_CREDITS_PLAN.md §2.3). What we actually paid, and who to. Without
  -- these three columns "realized gross margin per action" is unanswerable, and a prompt
  -- regression that triples output tokens is invisible until the monthly invoice lands.
  --
  -- These stay TEXT rather than getting the surrogate treatment action_id got, deliberately:
  -- they are free-form PROVENANCE, not join keys. Model ids churn (dall-e-3 removed, gpt-image-1
  -- deprecating) and prompt_version changes every time we touch a prompt, so their cardinality
  -- grows without a bounded lookup to point at. A lookup table here would be a table nobody
  -- maintains, protecting a column nobody filters on in the hot path.
  provider          text,                                    -- 'openai' | 'anthropic' | 'meshy' | ...
  model             text,                                    -- exact model id served
  prompt_version    text,                                    -- most quality movement comes from prompts, not models
  provider_cost_inr numeric(12,4),
  idempotency_key   text,                                    -- a retried request must not double-charge
  note              text,
  created_at        timestamptz not null default now(),
  settled_at        timestamptz,                             -- when it left 'reserved'
  constraint credit_transactions_split_matches
    check (credits = allowance_credits + wallet_credits),
  constraint credit_transactions_sign_matches_kind
    check ((kind = 'debit' and credits < 0) or (kind <> 'debit' and credits >= 0)),
  constraint credit_transactions_only_debits_reserve
    check (state = 'committed' or kind = 'debit')
);

-- The hot read: this baker's rows for the current month (allowance) and all-time (wallet).
create index if not exists credit_transactions_baker_created_idx
  on credit_transactions (baker_id, created_at desc);

-- Reservations left dangling by a crashed request — the sweep's exact query. Partial, so it
-- stays tiny: settled rows (the overwhelming majority) are not in it.
create index if not exists credit_transactions_reserved_idx
  on credit_transactions (created_at) where state = 'reserved';

-- Idempotency is only meaningful when a key is supplied.
create unique index if not exists credit_transactions_idempotency_idx
  on credit_transactions (idempotency_key) where idempotency_key is not null;

-- ── 3. reserve → commit / release ───────────────────────────────────────────────────
-- Supabase's JS client has no transactions, so the read-decide-insert has to happen inside
-- the database or it is a race. Two requests reading the same balance and both inserting a
-- debit is not a theoretical concern: the designer fires these from a UI where double-clicks
-- are normal.
--
-- pg_advisory_xact_lock serialises per BAKER (not globally) for the duration of the enclosing
-- transaction — the function's own, since Supabase calls it as a single statement.

create or replace function reserve_ai_credits(
  p_baker_id        uuid,
  p_action_key      text,
  p_allowance       integer,                 -- resolved ai_credits_per_month; null = unlimited
  p_order_id        uuid    default null,
  p_idempotency_key text    default null,
  p_note            text    default null
)
returns table (
  transaction_id bigint,
  ok             boolean,
  reason         text,
  cost           integer,
  from_allowance integer,
  from_wallet    integer
)
language plpgsql
as $$
declare
  v_cost        integer;
  v_action_id   smallint;
  v_month_start timestamptz;
  v_used        integer;
  v_wallet      integer;
  v_left        integer;
  v_take_allow  integer;
  v_take_wallet integer;
  v_id          bigint;
  v_prev        credit_transactions%rowtype;
begin
  -- Replay of an already-accepted request → return the original decision, charge nothing more.
  if p_idempotency_key is not null then
    select * into v_prev from credit_transactions t where t.idempotency_key = p_idempotency_key;
    if found then
      return query select v_prev.id, (v_prev.state <> 'released'), 'REPLAY'::text,
                          -v_prev.credits, -v_prev.allowance_credits, -v_prev.wallet_credits;
      return;
    end if;
  end if;

  select c.id, c.credits into v_action_id, v_cost from credit_costs c
   where c.action_key = p_action_key and c.is_active;
  if v_cost is null then
    return query select null::bigint, false, 'UNKNOWN_ACTION'::text, 0, 0, 0;
    return;
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_baker_id::text, 0));

  -- Start of the current calendar month, in IST, as an absolute instant.
  v_month_start := date_trunc('month', now() at time zone 'Asia/Kolkata') at time zone 'Asia/Kolkata';

  select coalesce(-sum(t.allowance_credits), 0) into v_used
    from credit_transactions t
   where t.baker_id = p_baker_id and t.state <> 'released' and t.created_at >= v_month_start;

  select coalesce(sum(t.wallet_credits), 0) into v_wallet
    from credit_transactions t
   where t.baker_id = p_baker_id and t.state <> 'released';

  if p_allowance is null then
    -- Unlimited plan: bill the whole cost to the allowance so the wallet is untouched and the
    -- ledger still records what the action cost us (the margin guardrail needs that either way).
    v_take_allow  := v_cost;
    v_take_wallet := 0;
  else
    v_left        := greatest(p_allowance - v_used, 0);
    v_take_allow  := least(v_left, v_cost);
    v_take_wallet := v_cost - v_take_allow;
    if v_take_wallet > v_wallet then
      return query select null::bigint, false, 'INSUFFICIENT_CREDITS'::text, v_cost, v_left, v_wallet;
      return;
    end if;
  end if;

  insert into credit_transactions
    (baker_id, kind, state, action_id, credits, allowance_credits, wallet_credits,
     order_id, idempotency_key, note)
  values
    (p_baker_id, 'debit', 'reserved', v_action_id, -v_cost, -v_take_allow, -v_take_wallet,
     p_order_id, p_idempotency_key, p_note)
  returning id into v_id;

  return query select v_id, true, null::text, v_cost, v_take_allow, v_take_wallet;
end;
$$;

-- The baker kept the result → the reservation becomes a real charge, stamped with what it
-- actually cost us. Idempotent: committing an already-committed row succeeds and does not
-- overwrite the cost already recorded.
create or replace function commit_ai_credits(
  p_transaction_id    bigint,
  p_provider          text    default null,
  p_model             text    default null,
  p_prompt_version    text    default null,
  p_provider_cost_inr numeric default null
)
returns boolean
language plpgsql
as $$
declare v_state text;
begin
  select state into v_state from credit_transactions where id = p_transaction_id;
  if v_state is null then return false; end if;
  if v_state = 'committed' then return true; end if;   -- replay
  if v_state = 'released'  then return false; end if;  -- a released reservation cannot be revived

  update credit_transactions
     set state             = 'committed',
         settled_at        = now(),
         provider          = coalesce(p_provider,          provider),
         model             = coalesce(p_model,             model),
         prompt_version    = coalesce(p_prompt_version,    prompt_version),
         provider_cost_inr = coalesce(p_provider_cost_inr, provider_cost_inr)
   where id = p_transaction_id;
  return true;
end;
$$;

-- The call failed, or the baker discarded the result → the hold evaporates. The row stays as
-- the record of an attempt WE paid for. Only a reservation can be released; refunding a real
-- charge is a separate, positive row (refund_ai_credits) so the two never look alike in the
-- audit trail.
create or replace function release_ai_credits(
  p_transaction_id bigint,
  p_note           text default null
)
returns boolean
language plpgsql
as $$
declare
  v_state text;
begin
  select state into v_state from credit_transactions where id = p_transaction_id;
  if v_state is null      then return false; end if;
  if v_state = 'released' then return true;  end if;   -- replay
  if v_state = 'committed' then return false; end if;

  update credit_transactions
     set state      = 'released',
         settled_at = now(),
         note       = coalesce(p_note, note)
   where id = p_transaction_id;
  return true;
end;
$$;

-- Give back a charge that was already committed — a support gesture, a quality failure found
-- after the fact. Mirrors the original split so the credits return to the pool they came from.
create or replace function refund_ai_credits(
  p_transaction_id bigint,
  p_note           text default null
)
returns bigint
language plpgsql
as $$
declare
  v_row credit_transactions%rowtype;
  v_id  bigint;
begin
  select * into v_row from credit_transactions where id = p_transaction_id;
  if not found or v_row.kind <> 'debit' or v_row.state <> 'committed' then return null; end if;

  insert into credit_transactions
    (baker_id, kind, state, action_id, credits, allowance_credits, wallet_credits,
     order_id, note, settled_at)
  values
    (v_row.baker_id, 'refund', 'committed', v_row.action_id,
     -v_row.credits, -v_row.allowance_credits, -v_row.wallet_credits,
     v_row.order_id, coalesce(p_note, 'refund of #' || v_row.id), now())
  returning id into v_id;
  return v_id;
end;
$$;

-- What the balance UI reads. Same month arithmetic as the reserve path, in one place, so the
-- number the baker is shown and the number the gate enforces can never disagree.
create or replace function ai_credit_balance(p_baker_id uuid, p_allowance integer)
returns table (allowance_used integer, allowance_left integer, wallet_balance integer)
language sql
stable
as $$
  with bounds as (
    select date_trunc('month', now() at time zone 'Asia/Kolkata') at time zone 'Asia/Kolkata' as month_start
  ),
  used as (
    select coalesce(-sum(t.allowance_credits), 0)::integer as v
      from credit_transactions t, bounds b
     where t.baker_id = p_baker_id and t.state <> 'released' and t.created_at >= b.month_start
  ),
  wallet as (
    select coalesce(sum(t.wallet_credits), 0)::integer as v
      from credit_transactions t
     where t.baker_id = p_baker_id and t.state <> 'released'
  )
  select used.v,
         case when p_allowance is null then null::integer else greatest(p_allowance - used.v, 0) end,
         wallet.v
    from used, wallet;
$$;

-- ── 4. orders: the AI's reading of a reference photo ────────────────────────────────
-- A manual order has design_snapshot = null — that NULL is the canonical "no design" signal
-- the whole app reads (see supabase/orders_design_snapshot_nullable.sql). These columns give
-- such an order enough structure to run the EXISTING X-Ray pipeline over, without disturbing
-- that signal.
--
-- WHY NOT JUST WRITE INTO design_snapshot: because design_snapshot = null is load-bearing.
-- The reference-photo gallery renders only while it is null (OrdersPanel.jsx), and Edit-in-3D
-- enables only when it is set. Populating it from an estimate would hide the customer's own
-- photo — the one piece of ground truth on the order — and light up a 3D editor over a design
-- nobody authored. X-Ray instead resolves design_snapshot ?? xray_spec_edited ??
-- xray_spec, and the order stays a photo order.
--
-- WHY THREE COLUMNS AND NOT ONE — this is the part that is expensive to add later:
-- xray_spec is written ONCE and never updated. Baker corrections go to
-- xray_spec_edited. The diff between them is a continuously-accruing, human-labelled
-- evaluation set on real customer photos: which fields the model gets wrong, how often, and
-- whether a cheaper model would do. Overwrite the estimate in place and that data never
-- exists — and the "which model?" question gets re-opened in six months with no more
-- evidence than today. Nothing else in this migration is irreversible; this is.
alter table orders add column if not exists xray_spec        jsonb;
alter table orders add column if not exists xray_spec_meta   jsonb;
alter table orders add column if not exists xray_spec_edited jsonb;

comment on column orders.xray_spec is
  'IMMUTABLE model output for a reference-photo order, in design_snapshot shape. Never updated in place — a regenerate replaces it only via an explicit new estimate, and corrections belong in xray_spec_edited.';
comment on column orders.xray_spec_meta is
  '{ provider, model, prompt_version, confidence, credit_transaction_id, created_at } — provenance for the estimate above.';
comment on column orders.xray_spec_edited is
  'Baker-corrected copy of xray_spec. NULL until they change something. estimate vs edited is the accuracy signal.';

-- Only photo orders carry an estimate, so a partial index stays small.
create index if not exists orders_xray_spec_idx
  on orders (baker_id) where xray_spec is not null;
