-- ── 023: AI credit packs (top-ups) ──────────────────────────────────────────────────
-- Lets a baker BUY credits when the monthly allowance runs out, instead of waiting for the
-- window to roll or upgrading a whole plan tier. Extends 022; no change to how the allowance
-- pool works. Rationale: docs (spattoo-core) AI_CREDITS_PLAN.md §2.3.
--
-- Apply manually to dev/prod Supabase (no migration runner). Safe to re-run.
--
-- ── WHERE PURCHASED CREDITS LIVE ────────────────────────────────────────────────────
-- Nowhere new. 022 already models two pools, and a purchase is simply a positive row in the
-- WALLET pool (kind='purchase', wallet_credits > 0). Which means the whole spend path —
-- reserve, commit, release, the balance function, allowance-first ordering — needs no change
-- at all: a top-up is just more wallet, and reserve_ai_credits already falls through to the
-- wallet once the allowance is exhausted.
--
-- The two pools stay distinct because they behave differently, and the difference is money:
-- the monthly allowance is a COST CEILING that resets and does not roll over; purchased
-- credits are PREPAID MONEY that persists. Allowance is always spent first, so a baker never
-- burns credits they paid for while free ones remain.
--
-- ── PURCHASED CREDITS NEVER EXPIRE (decided 2026-07-29) ─────────────────────────────
-- No expiry column, no expiry sweep, and none should be added. Purchased credits are prepaid
-- money; expiring them is a goodwill problem in a market where the baker is a one-person
-- business, and it would have to be STATED AT THE POINT OF PURCHASE to be enforceable at all —
-- so it could never be retrofitted onto packs already sold.
--
-- The cost of this is bounded and already paid for: GST on a pack is due at SALE, not at
-- redemption (see below), so credits sitting unredeemed forever are not a growing tax
-- liability — they are margin that has already been taxed. The only real exposure is the
-- provider cost if a baker burns a two-year-old balance in one week, and the allowance-first
-- spend order plus the per-action margin floor already bound that.
--
-- ── ⚠️ GST — NOT WIRED HERE ─────────────────────────────────────────────────────────
-- The supply is identifiable at issue (these credits are only ever redeemable for Spattoo AI
-- features), so time of supply is the DATE OF SALE, not the date of redemption: GST is due on
-- the pack, at purchase, at the same 18% as the subscription. services/billingEvents.js
-- already raises exactly one durable sale event per subscription charge for the accounting
-- system — a pack sale needs the same treatment, but emitSaleEvent()'s payload is
-- subscription-shaped (plan_id, billing_period_id, period_months). Bending a pack into those
-- fields would put a lie in the accounting feed. See the note in routes/aiCredits.js; it needs
-- a sibling emitter before packs are sold to a real baker.

-- ── 1. credit_packs — the shelf, as DATA ────────────────────────────────────────────
-- Prices live here and NOWHERE else. Unlike subscriptions (which need a pre-created Razorpay
-- plan id per tier/period), a top-up is a one-time Razorpay ORDER for an arbitrary amount —
-- so this table is the sole source of truth for what a pack costs, and the order amount is
-- read FROM here at checkout. The client sends a pack key, never an amount.
--
-- Compact surrogate id for the same reason credit_costs has one: credit_transactions
-- references it, and that table grows forever.
create table if not exists credit_packs (
  id          smallint    generated by default as identity primary key,
  pack_key    text        not null unique,                 -- 'topup_300'
  credits     integer     not null check (credits > 0),
  price_paise integer     not null check (price_paise > 0),-- Razorpay's subunit, like subscription_plans
  label       text        not null,                        -- what the baker sees on the button
  is_active   boolean     not null default true,           -- retire a pack without losing its sales history
  sort_order  smallint    not null default 0,
  updated_at  timestamptz not null default now()
);

-- Seed packs. ILLUSTRATIVE — priced at ~Rs.1/credit to match the peg in AI_CREDITS_PLAN.md
-- §2.3 (1 credit ~= Rs.1 of retail value), with a mild volume discount up the range. GST is
-- EXCLUSIVE here, consistent with how subscription_plans stores its prices.
--
-- The UI must render these as JOBS, not credits — "+20 build guides · Rs.299", never
-- "300 credits · Rs.299" (SUBSCRIPTION_TIERS.md: name the job, never the abstraction). The
-- balance endpoint already returns the per-action division needed to do that.
insert into credit_packs (pack_key, credits, price_paise, label, sort_order) values
  ('topup_150',  150,  14900, 'Small top-up',  1),
  ('topup_400',  400,  34900, 'Medium top-up', 2),
  ('topup_1000', 1000, 79900, 'Large top-up',  3)
on conflict (pack_key) do update
  set credits = excluded.credits, price_paise = excluded.price_paise,
      label = excluded.label, sort_order = excluded.sort_order, updated_at = now();

-- ── 2. credit_transactions: which pack a purchase was ───────────────────────────────
-- Null on every row that is not a purchase. The Razorpay payment id is NOT a column: it goes
-- in the existing idempotency_key, whose unique index is already exactly the dedupe a webhook
-- needs (Razorpay redelivers, and a redelivery must not mint credits twice).
alter table credit_transactions add column if not exists pack_id smallint references credit_packs (id);

-- ── 3. Recording a purchase ─────────────────────────────────────────────────────────
-- A function rather than a plain insert from JS, for one reason: the idempotency has to be a
-- race, not a check-then-insert. Two concurrent webhook redeliveries would both read "no row
-- for this payment id" and both insert. Here the unique violation IS the dedupe — we catch it
-- and return the row that won, so the loser is a no-op rather than an error the webhook
-- retries forever.
--
-- Returns the transaction id (new or pre-existing), or null if the pack is unknown/inactive.
create or replace function purchase_ai_credits(
  p_baker_id        uuid,
  p_pack_key        text,
  p_idempotency_key text,                       -- razorpay_payment_id
  p_note            text default null
)
returns bigint
language plpgsql
as $$
declare
  v_pack_id smallint;
  v_credits integer;
  v_id      bigint;
begin
  select p.id, p.credits into v_pack_id, v_credits
    from credit_packs p where p.pack_key = p_pack_key and p.is_active;
  if v_pack_id is null then return null; end if;

  begin
    insert into credit_transactions
      (baker_id, kind, state, pack_id, credits, allowance_credits, wallet_credits,
       idempotency_key, note, settled_at)
    values
      (p_baker_id, 'purchase', 'committed', v_pack_id, v_credits, 0, v_credits,
       p_idempotency_key, p_note, now())
    returning id into v_id;
  exception when unique_violation then
    -- A redelivered webhook. The first one already credited the baker; hand back its row.
    select t.id into v_id from credit_transactions t where t.idempotency_key = p_idempotency_key;
  end;

  return v_id;
end;
$$;
