-- ── 086: which edible prints were made for which order ──────────────────────────────────────────
--
-- A generated print lands in `baker_uploads` — it is the baker's, reusable on any future sheet, and
-- deliberately NOT a `cake_elements` row (it is printed, not placed on a 3D cake). That was right and
-- stays right. What was missing is the other half: the baker presses "Make it" inside an ORDER, then
-- opens that order's **Print & cut-outs** and the print is not there, because nothing recorded which
-- order it came from.
--
-- ── A LINK TABLE, NOT A COLUMN ON baker_uploads ─────────────────────────────────────────────────
-- `source_order_id` on the upload would say "this print belongs to that order", and the whole point
-- of putting prints in uploads is that they DO NOT. A goose printed for one baby shower is printed
-- again for the next one; a column forces a single answer and quietly re-poses the question the
-- upload was meant to settle.
--
-- Many-to-many says what is true: this print was used on these orders. Reuse adds a row rather than
-- overwriting one, and the print's own life is untouched — delete the link and the image is still
-- the baker's.
--
-- ── baker_id is DENORMALISED, on purpose ────────────────────────────────────────────────────────
-- It is derivable from either side, and it is here so a tenant fence is one predicate rather than a
-- join. Same reason `baker_uploads` carries it. ⚠️ It must agree with BOTH parents; the route sets
-- all three from server-resolved values (req.bakerId), never from a request body.
--
-- ON DELETE CASCADE both ways: the link is a fact ABOUT the pair. If the order goes, "printed for
-- that order" is meaningless; if the upload goes, there is nothing to show. Neither cascade reaches
-- the other parent — deleting a link never deletes an image.

create table if not exists public.order_edible_prints (
  id         bigint      generated by default as identity primary key,
  order_id   uuid        not null references public.orders(id)         on delete cascade,
  upload_id  bigint      not null references public.baker_uploads(id)  on delete cascade,
  baker_id   uuid        not null references public.bakers(id)         on delete cascade,
  -- What the identify step called it. Kept here rather than read off the upload's `name`, because a
  -- baker may rename the upload later and the order should still say what it was made for.
  label      text,
  created_at timestamptz not null default now(),
  -- Pressing "Make it" twice for the same decoration is one print on this order, not two.
  unique (order_id, upload_id)
);

comment on table public.order_edible_prints is
  'Which generated edible prints were made for which order. The print itself lives in baker_uploads '
  'and is reusable; this records where it was used. Written by routes/ediblePrints.js.';

-- The read is always "the prints for THIS order", so that is the index. The unique constraint above
-- already covers (order_id, upload_id), which serves this too — but state it, because a later
-- migration dropping the constraint would silently take the index with it.
create index if not exists order_edible_prints_order_idx
  on public.order_edible_prints (order_id);

-- Expect: a new empty table, and both foreign keys present.
select conname, confrelid::regclass as references
  from pg_constraint
 where conrelid = 'public.order_edible_prints'::regclass and contype = 'f'
 order by conname;
